### ISSUE TITLE
Apple Music

### ISSUE THREAD

**Issue by MayuraVerma** [dropcreations/Apple-Music-Tagger#3]
Does Apple Music app on iPhone show these credits tag for locally saved m4a?
Such as Lyricist

Does iTunes/Apple music on Mac, read/sync .lrc file Apple Music app on iPhone for locally saved m4a?

Or is program geared to get the credits from Apple music n save in m4a and read it on other app (non-Apple Music)

**Comment by dropcreations** [comment]
@MayuraVerma Basically this program is created for get credits and lyrics from Apple Music for other applications and the ones who need the information. iTunes reads some information but not all.

**Comment by MayuraVerma** [comment]
Does iTunes read these new credits like Lyricist from m4a?

How about lyrics from .lrc file?
